# Generated by Django 3.2.10 on 2023-04-18 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230415_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNeighborhood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_neighborhood_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPricerange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_price_range_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='property',
            name='featured_property',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='False'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('pending', 'PENDING'), ('sold', 'SOLD')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('property_neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertyneighborhood')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertytype')),
                ('property_type_price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertypricerange')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_listing_image_main', models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/')),
                ('property_listing_image_all', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertyneighborhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_price_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.propertypricerange'),
        ),
    ]
