# Generated by Django 3.2.10 on 2023-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230418_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='property_image_type',
            field=models.CharField(choices=[('Main', 'Main'), ('All', 'All')], default='All', max_length=20),
        ),
    ]
