# Generated by Django 3.2.10 on 2023-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230423_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ('property_id',)},
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property_listing_image_All',
            field=models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/'),
        ),
    ]
