# Generated by Django 3.2.10 on 2023-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230424_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image_1',
            field=models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image_2',
            field=models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image_3',
            field=models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image_main',
            field=models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/'),
        ),
    ]
